### ISSUE TITLE
rc1 default template not generating the same as beta8

### ISSUE THREAD

**Issue by madmunsterdaddy** [aspnet/Announcements#117]
(mostly) identical html/bootstrap is not rendering the same in the default template. see images. all I did was create a beta8 mvc with individual account, and the same in rc1

![car](https://cloud.githubusercontent.com/assets/15947066/11308164/dc6b3c72-8f79-11e5-90bc-35385476cb9d.png)
![check](https://cloud.githubusercontent.com/assets/15947066/11308168/dea8eade-8f79-11e5-8188-cbe23d3b2d94.png)

**Comment by mikehaas763** [comment]
I guess the sentence I just suggested be added to the top of the readme isn't obvious enough :smile:
