### ISSUE TITLE
Where to post issues?

### ISSUE THREAD

**Issue by Ph47** [aspnet/Announcements#128]
According to https://github.com/aspnet/Announcements/blob/master/CONTRIBUTING.md i have posted an issue: https://github.com/aspnet/PlatformAbstractions/issues/1. But project is almost empty now and no one responds to issue.

My posted Issue listed below:
---------------

I am writing here because of https://github.com/aspnet/Announcements/blob/master/CONTRIBUTING.md. 

As stated here (https://github.com/aspnet/Announcements/issues/104) IApplicationShutdown must be located in Microsoft.Extensions.PlatformAbstractions.
 
I have following dependency: "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-*" ("*" is 16258 now). It really contains some interfaces but does not contains IApplicationShutdown.

What is right way to catch app shutdown in asp vnext?

**Comment by davidfowl** [comment]
aspnet/Home is the right place for issues
