### ISSUE TITLE
Split function not working

### ISSUE THREAD

**Issue by nrkarthick** [aspnet/Announcements#129]
var temp = "123456-12569";
var test = temp.Split('-').Last();

After upgrading to RC1, split function is not working.

'StringValues' does not contain a definition for 'Split' and no extension method 'Split' accepting a first argument of type 'StringValues' could be found (are you missing a using directive or an assembly reference?)

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/blob/master/README.md
