### ISSUE TITLE
Configure custom config section breaking change in RC2

### ISSUE THREAD

**Issue by rohitshrivastava04** [aspnet/Announcements#130]
Hi 

I had a running configuration with RC1 but as soon as I upgraded to RC2, there is a compile time error.

Seems like IServiceCollection.Configure<T> started taking Action<T> whereas it used to take IConfigurationSection.

    Error	CS1503	Argument 2: cannot convert from 'Microsoft.Extensions.Configuration.IConfigurationSection' to 'System.Action<MyCustomTyppe>'	

Is there any easy way to fix this or I have to write a function which will convert IConfigurationSection to my custom type?

**Comment by MaximRouiller** [comment]
https://github.com/aspnet/Announcements/blob/master/README.md#announcements

**Comment by fmarcoux96** [comment]
@rohitshrivastava04 Please file any issues in aspnet/Home repo.

**Comment by rohitshrivastava04** [comment]
Ah my bad, sorry for it. Closing now.
