### ISSUE TITLE
Issue98-TcpClient missing in dotnet5.4 but in dotnet5.5 for "System.Net.Sockets"

### ISSUE THREAD

**Issue by zhangxin511** [aspnet/Announcements#133]
@Eilon I am recently update the target framework from dnxcore50 to dotnet5.4 based on your annoucement "Switching to new ‘dotnet’ target framework monikers", when we are updating to rc1-final/update1

One of our class library using TcpClient in System.Net.Sockets. When I update to dotnet5.4, it won't build because it cannot find TcpClient. After change our project.json from dotnet5.4 to dotnet5.5 it working fine. So what is the best practice for this? Should I change my project.json to dotnet5.5 and change  #if DNXCORE50 to #if DOTNET5_5 for ALL my other library? 

It seems on nuget.org only System.Net.Sockets support 5.4 and 5.5, all other packages only support dotnet5.4, what is the compatibility here?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/blob/master/README.md
