### ISSUE TITLE
AccessDeniedPath issues redirect?

### ISSUE THREAD

**Issue by sweeperq** [aspnet/Announcements#136]
One of the things that has always thrown me off about error handling in ASP.net is how it always seems to do a 302 redirect to a display page with a 200 OK status. I'm being visibly shown there is an error with the HTML response, but if I'm a spider/bot I don't know that because I never receive the correct HTTP status code.

I'm just curious if there is a reason that **AccessDeniedPath** follows this same pattern? Why doesn't it do something similar to how **app.UseStatusCodePagesWithReExecute()** works? That one returns the correct HTTP code and executes the page within the current request.

Or, is it really supposed to be a redirect and I should just manually change the HTTP status code of the resulting view using  **Response.StatusCode=403;**?

**Comment by davidfowl** [comment]
This repository isn't for asking questions, please see the readme and use aspnet/Home for questions.

**Comment by sweeperq** [comment]
Sorry David. I had done a search for CookieAuthentication and AccessDeniedPath and it led me to this Repo. Thanks for directing me over to aspnet/Home.
