### ISSUE TITLE
Identity in RC1 Update

### ISSUE THREAD

**Issue by nrkarthick** [aspnet/Announcements#138]
In beta7, i used EF 6.1.3 with oracle code first and in my startup class under Configure method I have `app.UseIdentity()` and its worked well (code as follows)

     Claim[] claims = SampleUser.Create_Claims(); // get claims
     var identity = new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme);
     ClaimsPrincipal principal = new ClaimsPrincipal(identity);
     await HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,  principal, new AuthenticationProperties() { IsPersistent = true });

But in RC1 it gives error to include services.AddIdentity() in the method ConfigureServices with application user and role.

I dont know how to use this application user and role in this new method.. 

Please guide me

**Comment by shahid-pk** [comment]
This repository is just for announcement please ask this question in aspnet/identity repo. Also read the read me of this repo . Thanks

**Comment by nrkarthick** [comment]
sorry.. I posted my ques in the respective section.. thanks
