### ISSUE TITLE
how to export asp.net vnext project (library) for UAP?

### ISSUE THREAD

**Issue by endink** [aspnet/Announcements#162]
i try to use:
···javascript
"netstandard1.5": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8",
        "uap10.0" 
      ],
      "dependencies": {
        "System.Net.Http": "4.0.1-rc2-23826"
      }
    }
···
after built, it cant add to UAP project, how to reuse my code ? Is there a document for "imports" section in project.json, thanks!

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/blob/master/README.md
