### ISSUE TITLE
ASP.NET/EF Core feeds renamed and moved to dotnet.myget.org

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Announcements#199]
The ASP.NET and EF Core MyGet feeds have moved from www.myget.org to dotnet.myget.org. There are automatic redirects from the old feeds to the new feeds so no _immediate_ change is needed. If you use the nightly feeds for packages, please move to the new feeds ASAP. The redirects will be available for at least a few weeks.

| https://www.myget.org/f/ (Before) | https://dotnet.myget.org/f/ (After) |
| --- | --- |
| aspnetvnext | aspnetcore-dev |
| aspnetrelease | aspnetcore-release |
| aspnetmaster | aspnetcore-master |
| aspnetcidev | aspnetcore-ci-dev |
| aspnetcirelease | aspnetcore-ci-release |

Please use https://github.com/aspnet/Home/issues/1708 for further discussion.

**Comment by natemcmaster** [comment]
This is no longer relevant. See https://github.com/aspnet/Announcements/issues/293 and https://github.com/aspnet/Announcements/issues/282
