### ISSUE TITLE
Breaking Logging changes and new additions

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Announcements#238]
### Obsolete APIs: ###
Obsoleted `AddProvider` on `ILoggerFactory`
- All `Add*(...)` provider extension methods are now obsolete with replacements on `Microsoft.Extensions.Logging.LoggerFactory`.
- The `AddConsole` `AddDebug` etc. provider extension methods that took a filter or minimum `LogLevel` are now obsolete

**No longer shipping `Microsoft.Extensions.Logging.Filter`.**

### First Class Filtering ###
`LoggerFactory` now has multiple `AddFilter(...)` overloads.

Filters use provider names, categories, and log level to filter logs.

There is an `AddProvider(string providerName, ILoggerProvider provider)` function to add providers with a custom name used for filtering.

Custom provider names are checked first when filtering. then provider full names are checked i.e.
Check `Console` as the custom name then `Microsoft.Extensions.Logging.Console.ConsoleLoggerProvder` as the full name.

Old:
```c#
var loggerFactory = new LoggerFactory();
loggerFactory = loggerFactory.WithFilter(new FilterLoggerSettings
{
    { "Microsoft", LogLevel.Warning },
    { "System", LogLevel.Error }
});
loggerFactory.AddConsole();
```

New:
```c#
var loggerFactory = new LoggerFactory();
loggerFactory.AddFilter(new Dictionary<string, LogLevel>
{
    { "Microsoft", LogLevel.Warning },
    { "System", LogLevel.Error }
});
loggerFactory.AddConsole();
```

The `AddDebug()` `AddConsole()` etc. methods we provide have predefined custom provider names:
- Console
- Debug
- EventLog
- AzureAppServices
- TraceSource
- EventSource

### Configuration ###
`LoggerFactory`'s constructor can take an `IConfiguration` and will create filters based on the config:
```json
{
  "Logging": {
    "LogLevel": {
        "System": "Trace",
        "Default": "Warning"
    },
    "Console": {
        "LogLevel": {
          "Microsoft.Extensions": "Warning"
        }
    },
    "CustomProvider": {
      "LogLevel": {
        "System": "Information"
      }
    }
  }
}
```
The configuration can also be replaced with `UseConfiguration` on `LoggerFactory`

The Logging system is configured via `IWebHostBuilder.ConfigureLogging`

Old:
```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory factory)
{
    factory.AddConsole();
    factory.AddDebug();
}
```

New:
```c#
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .ConfigureLogging(factory =>
        {
            factory.AddConsole();
            factory.AddDebug();
        }
        .etc...

    host.Run();
}
```

Please use aspnet/Logging#615 for any discussion.

**Comment by pakrym** [comment]
This is superseded by https://github.com/aspnet/Announcements/issues/255
