### ISSUE TITLE
NET Core 2.0.0-preview2 Log filtering issue

### ISSUE THREAD

**Issue by akarimovbytewerk** [aspnet/Announcements#254]
Hello, after upgrade to version 2.0.0-preview2 LoggerFactory filtering is broken and there is no method AddFilter anymore. Can you suggest how to filter built in event sources in new version or did i miss something?
Here is my ConfigureServices part:
`var loggerFactory = new LoggerFactory();
            loggerFactory.AddFilter(new Dictionary<string, LogLevel>
            {
                { "Microsoft", LogLevel.Warning },
                { "System", LogLevel.Error },
                { "Engine", LogLevel.Debug }
            });
            loggerFactory.AddLog4Net();`

**Comment by alexbocharov** [comment]
https://github.com/aspnet/Announcements/blob/master/README.md

You mast create issue to [aspnet/Logging](https://github.com/aspnet/Logging)

**Comment by akarimovbytewerk** [comment]
sorry, can you close this.

**Comment by akarimovbytewerk** [comment]
https://github.com/aspnet/Logging/issues/654
