### ISSUE TITLE
Alternatives to authentication branching

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Announcements#265]
I guess the most popular usage of authentication branching was to disable automatic challenge for a particular paths.
How can it be achieved now?

Maybe adding a property to AuthorizeAttribute will be the case?
Or some kind of authorization filter that will have a predicate to determine if challenge required?

@HaoK, @PinpointTownes

**Comment by davidfowl** [comment]
Please don't file issues on this repository. See the readme https://github.com/aspnet/Announcements/blob/master/README.md. Bugs should be opened on product repositories or on aspnet/Home.
