### ISSUE TITLE
Improved end to end testing support for MVC applications: Typo?

### ISSUE THREAD

**Issue by searus** [aspnet/Announcements#276]
Hi @javiercn, I think the constructor name is wrong in the first example code block in #275

Shouldn't it be 
```
        public MyApplicationFunctionalTests (WebApplicationTestFixture<Startup> fixture)
        {
            Client = fixture.Client;
        }
```

**Comment by hishamco** [comment]
@searus this repo for announcements only, please file an issue on MVC repo

**Comment by searus** [comment]
@hishamco I raised it here as it's an error in the announcement itself, not in MVC.

**Comment by smitpatel** [comment]
Updated.

**Comment by jnm2** [comment]
@hishamco, the problem is that so many people are watching this repo specifically for announcements and we don't want to be notified that you found a typo.  So even in this instance, reporting in the discussion repo would be the most considerate.
