### ISSUE TITLE
Model binding accesses read-only properties in post-back

### ISSUE THREAD

**Issue by mnmr** [aspnet/Announcements#297]
I have a simple edit model, which contains a few computed/read-only properties. When posting to a controller method, the model validation engine accesses these properties, causing an exception.

However, it does not make sense to access or attempt to validate a read-only property.

Additionally, all properties are marked with [BindNever], which seems to have no effect on this behavior.

The controller method takes a single parameter (the edit model) decorated with [FromForm].

Using 2.1.0-preview2-30355.

**Comment by suadev** [comment]
@mnmr You are on the wrong place bro.

**Comment by natemcmaster** [comment]
This repo is for team announcements only. See https://github.com/aspnet/announcements#announcements.

To file a bug or start a discussion, please find the appropriate repo in https://github.com/aspnet and create a new issue. 
For general issue discussions please go to https://github.com/aspnet/Home/issues and create a new issue.
