### ISSUE TITLE
Use [NotNull] and 'nameof' operator

### ISSUE THREAD

**Issue by hishamco** [aspnet/Announcements#30]
As we know ```[NotNull]``` is very helpful to avoid ```null``` checking and throw ```ArgumentNullException```, also using ```nameof``` operator is helpful too instead of magic strings, I have seen those widely in almost the repos, i already checked them before month ago and made the fix, nothing but i have notice the same thing happen last few weeks. I did the same fix again yesterday and today in almost the repos. Please can someone have a look and merge these changes:
https://github.com/aspnet/HttpAbstractions/pull/327
https://github.com/aspnet/WebSockets/pull/40
https://github.com/aspnet/SignalR-SqlServer/pull/13
https://github.com/aspnet/Testing/pull/123
https://github.com/aspnet/MusicStore/pull/498
https://github.com/aspnet/Mvc/pull/2690
https://github.com/aspnet/Security/pull/287
https://github.com/aspnet/SignalR-ServiceBus/pull/8
https://github.com/aspnet/FileSystem/pull/109 
https://github.com/aspnet/HttpClient/pull/26
https://github.com/aspnet/Identity/pull/485
~~https://github.com/aspnet/dnx/pull/2047~~

I hope you take this in mind before merge any PR to avoid such things in the future

**Comment by Eilon** [comment]
This repo is for announcing product changes, not discussing future work. We are working on clearing out PRs from all the repos. Thanks!

**Comment by hishamco** [comment]
Thanks for the clarification @Eilon
