### ISSUE TITLE
怎么找工作啊

### ISSUE THREAD

**Issue by ToLearnMoe** [aspnet/Announcements#304]
我学spirng的同学都上班两个月了我实习都没找到，学了给asp告诉我现在不能用了要什么点apsnet。你们行不行啊

!!! DO NOT POST ISSUES IN THIS REPO !!!
!!! DO NOT POST ISSUES IN THIS REPO !!!
!!! DO NOT POST ISSUES IN THIS REPO !!!
!!! DO NOT POST ISSUES IN THIS REPO !!!
!!! DO NOT POST ISSUES IN THIS REPO !!!

This repo is for team announcements only. See https://github.com/aspnet/announcements#announcements.

To file a bug or start a discussion, please find the appropriate repo in https://github.com/aspnet and create a new issue. 
For general issue discussions please go to https://github.com/aspnet/Home/issues and create a new issue.

**Comment by l2999019** [comment]
自己能力不行 怪技术？ 这态度 能找到实习才怪了

**Comment by kinosang** [comment]
ASP has already been deprecated many years ago.

Please remember that, it's never too old to learn.
