### ISSUE TITLE
Unable to download EF beta 5 not on NuGet

### ISSUE THREAD

**Issue by tuppers360** [aspnet/Announcements#38]
How do I get beta 5 for EF in VS 2015 RC??

**Comment by bricelam** [comment]
Does `Install-Package EntityFramework.SqlServer -Pre` work?

**Comment by tuppers360** [comment]
I tried  Install-Package EntityFramework.Core-Pre  and it now thinks beta 5 is the version in the NuGet manager but when I type:

PM> dnu restore

I get:

Microsoft .NET Development Utility CLR-x86-1.0.0-beta5-12103

Restoring packages for C:\Users\tuppe\Documents\Visual Studio 2015\Projects\AngularProject\src\AngularProject\project.json
  CACHE https://api.nuget.org/v3/index.json
  CACHE https://www.nuget.org/api/v2/
  GET https://nugetapiapps.blob.core.windows.net/ngx/entityframework/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='EntityFramework'
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.runtime/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  CACHE https://www.nuget.org/api/v2/package/System.Runtime/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.text.encoding/index.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding'
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.globalization/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Globalization'
  CACHE https://www.nuget.org/api/v2/package/System.Globalization/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.runtime.interopservices/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.InteropServices'
  CACHE https://www.nuget.org/api/v2/package/System.Runtime.InteropServices/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.threading.tasks/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks'
  CACHE https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.io/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO'
  CACHE https://www.nuget.org/api/v2/package/System.IO/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.reflection/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Reflection'
  CACHE https://www.nuget.org/api/v2/package/System.Reflection/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.collections/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections'
  CACHE https://www.nuget.org/api/v2/package/System.Collections/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.runtime.extensions/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Extensions'
  CACHE https://www.nuget.org/api/v2/package/System.Runtime.Extensions/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.linq.expressions/index.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Linq.Expressions'
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.threading/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading'
  CACHE https://www.nuget.org/api/v2/package/System.Threading/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.diagnostics.debug/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Debug'
  CACHE https://www.nuget.org/api/v2/package/System.Diagnostics.Debug/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.collections.concurrent/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections.Concurrent'
  CACHE https://www.nuget.org/api/v2/package/System.Collections.Concurrent/4.0.0-beta-23019
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.threading.threadpool/index.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.ThreadPool'
  OK https://nugetapiapps.blob.core.windows.net/ngx/entityframework/index.json 683ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.globalization/index.json 496ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.threading.tasks/index.json 493ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.reflection/index.json 487ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.text.encoding/index.json 517ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.io/index.json 493ms
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.text.encoding/4.0.0-beta-23019/system.text.encoding.4.0.0-beta-23019.nupkg
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.linq.expressions/index.json 487ms
  GET https://nugetapiapps.blob.core.windows.net/ngx/system.linq.expressions/4.0.0-beta-23019/system.linq.expressions.4.0.0-beta-23019.nupkg
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.runtime/index.json 584ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.collections/index.json 539ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.collections.concurrent/index.json 498ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.threading/index.json 539ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.runtime.interopservices/index.json 577ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.runtime.extensions/index.json 578ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.threading.threadpool/index.json 508ms
  CACHE https://www.nuget.org/api/v2/package/System.Threading.ThreadPool/4.0.10-beta-22231
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Linq.Expressions' 607ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding' 678ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.diagnostics.debug/index.json 841ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.text.encoding/4.0.0-beta-23019/system.text.encoding.4.0.0-beta-23019.nupkg 439ms
  OK https://nugetapiapps.blob.core.windows.net/ngx/system.linq.expressions/4.0.0-beta-23019/system.linq.expressions.4.0.0-beta-23019.nupkg 450ms
dnu : Unable to locate EntityFramework >= 7.0.0-beta5
At line:1 char:1
+ dnu restore
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to locat... >= 7.0.0-beta5:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Writing lock file C:\Users\tuppe\Documents\Visual Studio 2015\Projects\AngularProject\src\AngularProject\project.lock.json
Restore complete, 2791ms elapsed
Errors in C:\Users\tuppe\Documents\Visual Studio 2015\Projects\AngularProject\src\AngularProject\project.json


    Unable to locate 
EntityFramework
 >= 7.0.0-beta5

**Comment by tuppers360** [comment]
Looking at NuGet the latest build on there is beta4 so guess that explains why I cant download it

**Comment by glen-84** [comment]
@tuppers360 Why are you posting this in the **Announcements** repo?

Please move this to aspnet/Home, or better yet, ask the question on [JabbR](https://jabbr.net).

**Comment by Eilon** [comment]
Indeed, closing this here. For EF issues please ask on the EntityFramework repo, for general issues ask on the Home repo, or better yet, StackOverflow.
