### ISSUE TITLE
feature “Control Startup class activation” doesn't work

### ISSUE THREAD

**Issue by tatti9018** [aspnet/Announcements#442]
Help with feature “Control Startup class activation”
->

```
 var host = Host.CreateDefaultBuilder()
            .ConfigureWebHost(builder =>
            {
                builder.UseStartup(context => new Startup(logger));
            })
            .Build();
```
When I use Project Sdk=”Microsoft.NET.Sdk.BlazorWebAssembly”, I get error: ‘IHostBuilder’ does not contain a definition for ‘ConfigureWebHostDefaults’
When I set Project Sdk=”Microsoft.NET.Sdk.Web”, project see ConfigureWebHostDefaults, but project doesn’t work….

**Comment by mkArtakMSFT** [comment]
This issue has been moved to https://github.com/dotnet/aspnetcore/issues/27040 by the author.
