### ISSUE TITLE
Set doesn't save

### ISSUE THREAD

**Issue by markburgessstl** [aspnet/Announcements#59]
currentLocatiom = System.IO.Directory.GetCurrentDirectory();

  var configurationBuilder = new ConfigurationBuilder(currentLocatiom).AddJsonFile("config.json");
   config = configurationBuilder.Build();
...
config.Set("access_token", accessToken);

the call to Set() seems to work, but the config file is not changed.

**Comment by glen-84** [comment]
@markburgessstl Why are you posting an issue in the **Announcements** repo?

Please read the [README](https://github.com/aspnet/Announcements/blob/master/README.md).

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Configuration#283
