### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by gvx111** [aspnet/Announcements#75]
How to setting the DNX_NO_MIN_VERSION_CHECK environment variable to 1

**Comment by cH40z-Lord** [comment]
That depends entirely on your Operating System. However, as this is an *Announcements* repository only announcements should be posted here. Bug reports or questions like yours should be opened in the corresponding repositories. Or if you can't find one or aren't exactly sure which one is the best, feel free to open an issue in https://github.com/aspnet/Home
