### ISSUE TITLE
Breaking Change: ConfigureAuthentication => AddAuthentication

### ISSUE THREAD

**Issue by jmblakl** [aspnet/Announcements#82]
I was unable to find the rename of ConfigureAuthentication to AddAuthentication in the breaking change list.  Forgive me if I missed it.

**Comment by fmarcoux96** [comment]
Which authentication are you trying to configure?

Here's the methods:

In `Microsoft.AspNet.Security.Cookies`: `IAppBuilder.ConfigureCookieAuthentication()`
In `Microsoft.AspNet.Security.OpenId`: `IAppBuilder.ConfigureOpenIdAuthentication()`
In `Microsoft.AspNet.Security.{Provider}`: `IAppBuilder.Configure{Provider}Authentication()` (Like Facebook, Twitter, etc.)

If none of these is what you're searching, tell us more please.

**Comment by NeelBhatt** [comment]
It is not correct place to post issue as this repository is used for announcements.

**Comment by fmarcoux96** [comment]
@NeelBhatt If it's possible, migrate the issue. I'm not responsible for that, I just wanna help!

**Comment by HaoK** [comment]
Yeah this was removed and rolled into an overload of AddAuthentication which is the new pattern across Repos

**Comment by Eilon** [comment]
@HaoK in which release was this changed? Can you set the milestone on this issue?

**Comment by davidfowl** [comment]
We should make another issue with the details
