### ISSUE TITLE
Consider being more complete with the announcements

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Announcements#84]
The announcements for beta8 are missing some breaking changes.

The constructor for `ConfigurationBuilder` doesn't have a parameter for the base path anymore. Instead, there is a `SetBasePath` extension method.

For me, this came as quite the surprise: The scripts have been moved out of the publishing root into the `approot` folder. Anything relying on this location (like init scripts on Linux) need to be changed to reflect that.

**Comment by LeeCheneler** [comment]
While I didn't find this too much of a pain as I found the `SetBasePath` extension method quite quickly I do agree that it probably should have been listed as a breaking change. Unless it had already come under the umbrella of one? I'm sure I haven't checked them out extensively as only this and global exception handling had changed that affected us.

**Comment by davidfowl** [comment]
Pleas don't start discussions on this repository. Use aspnet/Home for general suggestions and questions.
