### ISSUE TITLE
forwardWindowsAuthToken in web.config causes problems on Azure

### ISSUE THREAD

**Issue by mkelley82** [aspnet/Announcements#95]
The forwardWindowsAuthToken attribute on the httpPlatform element in web.config causes a very hard to track down 502 CGI Error when publishing to Azure.  Perhaps it should be noted. @davidfowl did mention though that  "they are rolling out azure updates with the platform handler" and it should "go away soon". Hopefully, that's the case. But if not, atleast this will make people aware.

**Comment by davidfowl** [comment]
@mkelley82 Don't file new bugs on this repository. Please add this as a comment on https://github.com/aspnet/Hosting/issues/364
