### ISSUE TITLE
EF Logging in Beta 8 Seems to be missing

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Announcements#99]
In Beta 7 I could turn on Information logging (to the console or debug) and I would get detailed output from EF7, but in Beta 8 it's missing. Is this expected? I couldn't see anything in the release notes.

**Comment by tparnell8** [comment]
This is the announcements repo which according to readme.md is probably not the place to pose questions.

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/EntityFramework/issues/3624
